---
apiVersion: v1
kind: Service
metadata:
  name: store-eu-west-6
  namespace: store
  annotations:
    configsync.gke.io/cluster-name-selector: luca-eu-west-6
spec:
  selector:
    app: store
  ports:
    - port: 8080
      targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: store-eu-west-6
  namespace: store
  annotations:
    configsync.gke.io/cluster-name-selector: luca-eu-west-6